\c logai

CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY NOT NULL,
  company VARCHAR(50) UNIQUE NOT NULL,
  pw VARCHAR(99) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  phone VARCHAR(15) UNIQUE NOT NULL,
  npc VARCHAR(25) NOT NULL,
  comptype TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
  id SERIAL PRIMARY KEY NOT NULL,
  origin_id INTEGER REFERENCES users(id),
  content1 INTEGER REFERENCES inventory(id),
  date_ordered VARCHAR(12) NOT NULL,
  orderer VARCHAR(99) NOT NULL,
  fulfilled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory(
  id SERIAL PRIMARY KEY NOT NULL,
  warehouse_id INTEGER REFERENCES users(id),
  sku VARCHAR(20) NOT NULL,
  name VARCHAR(99) NOT NULL,
  picture VARCHAR(999),
  amount VARCHAR(99) NOT NULL
);
